name: Tests
on:
  pull_request:
    paths:
      - "**.rs"
      - "Cargo*"
      - ".github/workflows/**.yml"
      - ".github/.codecov.yml"
    branches:
      - "*"
jobs:
  test_unix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Test
        run: nix develop .#ci-tests --command cargo test --verbose --all
