name: Format code

on:
  push:
    branches:
      - main
    tags-ignore: ["v[0-9]+.[0-9]+.[0-9]+*"]
    paths:
      - "**.ts"
      - "**.tsx"
      - "**.js"
      - "**.mjs"
      - "**.cs"
      - ".github/workflows/**.yml"

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v4

      - uses: rrbutani/use-nix-shell-action@v1
        with:
          devShell: .#ci-format

      - name: Format project source code
        run: nix fmt

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply formatting changes
          status_options: "--untracked-files=no"
